FROM python:3.11-slim
RUN apt-get update -qq && apt-get install -y -qq curl vim coreutils && \
    pip install --no-cache-dir faker && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY data_writer_filebrowser.py ./filebrowser_curl_client_cycle_metrics.py
CMD touch file.py
CMD chmod 777 file.py
CMD ["python", "/app/filebrowser_curl_client_cycle_metrics.py"]
